[MAGIC_ENV]
Owner = 熊本コンピュータソフト株式会社
DateMode = J
InputPassword = N
NumberOfRecentProjects = 10
DefaultProject = %TB%Projects\SHIRAKI.edp
StartApplication = %TB%MCF\SHIRAKI.ecf
DeploymentMode = R
Terminal = 1
DefaultDatabase = Default Database
TempDatabase = Memory
ISAMTransaction = N
DeadlockPrevent = N
ThousandSeparator = ,
DecimalSeparator = .
DateSeparator = /
TimeSeparator = :
ScreenModePrompt = :
Century = 1950
BatchPaintTime = 1000
RangePopTime = 10
TempPopTime = 10
IdleTime = 300
TaskCacheSize = 0
ConfirmAutoExit = N
AllowCreateInModify = Y
AllowUpdateInQuery = N
LocateModeQueryWarning = Y
ResidentINI = N
LoadResidentFiles = N
DisplayFullMsgs = Y
CenterScreenInOnline = N
RepositionAfterModify = N
AccessEnvironment = Y
AccessColors = Y
AccessFonts = Y
AccessKeyboardMapping = Y
AccessServers = Y
AccessServices = Y
AccessVisualConnection = Y
AccessCommunications = Y
AccessDBMS = Y
AccessDatabases = Y
AccessLogging = Y
AccessLogicalNames = Y
AccessLanguages = Y
AccessPrinters = Y
AccessHTMLStyles = Y
AccessPrintAttributes = Y
AccessLogon = Y
AccessMobileDevicesList = Y
SystemLogin = N
AllowTesting = N
AccessPreferredEventList = Y
;
ConstFile = SUPPORT\mgconstw.jpn
HelpFile = SUPPORT\mghelpw.chm
StudioColorDefinitionFile = %SUPPORT%Clr_EXTEND2.jpn
RuntimeApplicationColorDefinitionFile = %SUPPORT%Clr_EXTEND.jpn
RuntimeInternalColorDefinitionFile = %SUPPORT%Clr_EXTEND.jpn
StudioFontDefinitionFile = %SUPPORT%fnt_std2.jpn
RuntimeApplicationFontDefinitionFile = %SUPPORT%fnt_std.jpn
RuntimeInternalFontDefinitionFile = %SUPPORT%fnt_std.jpn
StudioKeyboardMappingFile = %SUPPORT%act_std2.jpn
RuntimeKeyboardMappingFile = %SUPPORT%act_std.jpn
HTMLStyle = SUPPORT\html_std.jpn
PrintAttr = SUPPORT\prn_std.jpn
UsersPath = SUPPORT\usr_std.jpn
;OEM2AnsiFile = SUPPORT\OEM2Ansi.jpn
StartingLanguage =

DifferencesToolCommandLine =
;

ActivateRequestsServer = N
;Filters = HTTP_endusers:40% | SOAP_primary:10% | SOAP_secondary:5% | +
RemoteCalls:10% |COM:5%
MessagingServer = Default Broker

RequesterTimeout = 0

;WebDocumentPath = C:\Program Files\Magicxpa\Studio 4.8\Scripts
;InternetDispatcherPath = /Magic32Scripts/MgWebRequester.dll
;WebDocumentAlias = /scripts

FileHandles = 0
CommandProcessor = C:\WINDOWS\SysWOW64\cmd.exe
LockFile  = mglock.dat
ResourceLockFilePath = mgres.loc
LockWithinTran = Y
LicenseFile = C:\Program Files\Magicxpa\Studio 4.8\license.dat
LicenseName = MGCSTK4
TooltipTimeout = 5
AuthoringToolPath = Notepad.exe
MaxBookMarks = 10
MaxCrfResults = 5
MaxConcurrentRequests = 0
MaxConcurrentUsers = 0
ContextInactivityTimeout = 864000
ContextUnloadTimeout = 1200
RetryOperationTime = 600
GeneralErrorLog = mgerror.log
DefaultColor = 1
DefaultFont = 1

IOTiming = I
HTTPTimeout = 0
PBImagesNumber = 6
PalettesAlwaysOnTop = Y
DockablePalettes = Y
SingleExpandPalettes = N
AutomaticPropertySheet = F
LoadBalancingPriority = 3
MailConnectionTimeout = 0
MailOperationTimeout = 0
ImageCacheSize = 256
ImageCacheCheckTime = N
CheckerLevel = R
CheckerGroups = O
CheckerMessageTable = Support\chk_std.dat
CheckerJumpAuto = Y
CheckerUnusedExp = O
CheckerOutputFile =
DropUserFormats =
AccessCheckerMessages = Y
LdapAddress =
LdapConnectionString =
LdapDomainContext =
LdapTimeout = 0
CTLCacheFilesPath =
CTLCacheFilesAlias =
UseWindowsXPThemes = Y
OpenComponentsUsing = C
StudioStartupMode = W
DefaultSourceDir = Source
DefaultExportsDir = Exports
ExternalCodePage = 932
SoapClientModulesPath = SoapClientModules\
PrintCancel = N
ShortDescriptionChar=
;ApplicationPublicName=
;DefaultXMLEncoding=
RCCloseTaskOnParent = N
EnableRemoteDebugger =
RemoteDebuggerPort =
CacheSizeArrayFetch = 100
;SvcUtilPath = svcutil.exe
HTTPFramework = S
DPIAware = Y
PrintQueueDelimit=/

[MAGIC_SERVERS]
Default Broker = 0,,,,10,,1
DEFAULT = 0,,,,10,,9

[MAGIC_COMMS]
NONE = 1, 0, NO Parameters needed
TCP/IP = 2, 30, 1500-2000

[MAGIC_DBMS]
Btrieve = 1, NotAllowNull, 10.3, Btrieve Parameters, N, , NotLogSync, 0, +
1, NotCheckExist,
Pervasive = 2, NotAllowNull, 10.3, Pervasive Parameters, N, , NotLogSync, +
0, 0, NotCheckExist,
DB2 for IBM i(SQL) = 7, NotAllowNull, 10.3, CONNECTDLL=MGEAC32.DLL, N, , +
NotLogSync, 0, 0, NotCheckExist,
Oracle = 14, NotAllowNull, 10.3, Oracle Parameters,,,,,,,
DB2 for IBM i = 17, NotAllowNull, 10.3, MAGICDBA=MAGIC400 DBCS=IBM-943:IBM-+
5026 CRTSPLF=N, N, , NotLogSync, 1, 0, NotCheckExist,
ODBC = 20, NotAllowNull, 10.3, ODBC Parameters, D, , NotLogSync, 0, 0, +
NotCheckExist,
MicrosoftSQLServer = 21, NotAllowNull, 10.3, MicrosoftSQL Parameters,,,,0,0+
,,
Memory Tables = 22, NotAllowNull, 10.3, Memory Tables Parameters, N, , +
NotLogSync, 0, 0, NotCheckExist,
SQLite = 10, NotAllowNull, 10.3, SQLite Parameters, N, , NotLogSync, 0, +
1, CheckExist,
GigaSpaces = 3, NotAllowNull, 10.3, Space Parameters, N, , NotLogSync, 0, +
0, NotCheckExist,

[MAGIC_DATABASES]
Default Database = DBMS, 1, , %DATA%, , , , , MagicRecordLock, ChangeFileIn+
Toolkit, CheckDefinition, CheckKey, NoFileLocks, , , CheckExist, 0, , +
NoAS400SrvrSort, , NoWebServiceDB,
Memory = DBMS, 22, , , , , , , NoMagicRecordLock, ChangeFileInToolkit, +
NoCheckDefinition, NoCheckKey, NoFileLocks, , , NoCheckExist, 0, , +
NoAS400SrvrSort, , NoWebServiceDB,
SQLite Database = DBMS, 10, , sqlite.SQLite, , , , , NoMagicRecordLock, +
ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Default XML Memory Database = DBMS, 22, , , , , , , NoMagicRecordLock, +
ChangeFileInToolkit, NoCheckDefinition, NoCheckKey, NoFileLocks, FILE_CHUNK+
_SIZE=50, , NoCheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Default XML Database = XML, 0, , , , , , , NoMagicRecordLock, ChangeFileInT+
oolkit, CheckDefinition, CheckKey, FileLocks, , , NoCheckExist, 0, , +
NoAS400SrvrSort, , Default XML Memory Database
RIADEMO = DBMS, 10, , RIADemo.sqlite, , , , , NoMagicRecordLock, ChangeFile+
InToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , CheckExist, 0, , +
NoAS400SrvrSort, , NoWebServiceDB,
OnlineSamples = DBMS, 10, , OnlineSamples.sqlite, , , , , NoMagicRecordLock+
, ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
RIASamples = DBMS, 10, , RIASamples.sqlite, , , , , NoMagicRecordLock, +
ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Mobile Demo = DBMS, 10, , MobileDemo.sqlite, , , , , NoMagicRecordLock, +
ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Mobile Demo=DBMS, 10, , MobileDemo.sqlite, , , , , NoMagicRecordLock, +
ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
CheckExist, 0, , NoAS400SrvrSort,
Mobile Demo Local = DBMS, 11, , MobileDemoLocal.sqlite, , , , , NoMagicReco+
rdLock, DontChangeFileInToolkit, NoCheckDefinition, NoCheckKey, NoFileLocks+
, , , CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Mobile Demo Large = DBMS, 10, , MobileDemoLarge.sqlite, , , , , NoMagicReco+
rdLock, ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , +
, CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Mobile Demo Large Local = DBMS, 11, , MobileDemoLarge.sqlite, , , , , +
NoMagicRecordLock, DontChangeFileInToolkit, NoCheckDefinition, NoCheckKey, +
NoFileLocks, , , CheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,
Default Work = DBMS, 1, , %WRK%, , , , , NoMagicRecordLock, ChangeFileInToo+
lkit, CheckDefinition, CheckKey, FileLocks, , , NoCheckExist, 0, , +
NoAS400SrvrSort, , NoWebServiceDB,
MySQL Database = DBMS, 20, SHIRAKI, , SHIRAKI, , , , MagicRecordLock, +
DontChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , +
NoCheckExist, 0, , NoAS400SrvrSort, , NoWebServiceDB,

[MAGIC_LOGICAL_NAMES]
MG_SAMPLES = %EngineDir%SampleProjects
TB = C:\Projects\shiraki_project\
MCF = %TB%MCF\
DATA = %TB%DATA\
BMP = %TB%BMP\
WRK = %TB%WRK\
SUPPORT = %TB%SUPPORT\
TXT = %TB%TXT\
ENV = %TB%ENV\
ModelTable = %TB%MODELTABLE\
SubProjects = %TB%SubProjects\
Master = %TB%Master\
DLL = %TB%DLL\
PDF = %TB%PDF\


[MAGIC_LANGUAGE]
Runtime Messages = %EngineDir%SUPPORT\msg_rnt.jpn

[MAGIC_SERVICES]
Default Service = Default Broker,,,

[MAGIC_GATEWAYS]
MGDB00=Gateways\MGbtrieve.dll
;MGDB01=Gateways\MGPervasiveSQL.dll
;MGDB06=Gateways\MGdb2400.DLL
MGDB09=Gateways\mgsqlite.dll
;MGDB10=Gateways\mglocal.dll
;MGDB13=Gateways\MGoracle.dll
;MGDB16=Gateways\MGeac32.dll
;MGDB18=Gateways\MGdb2.DLL
MGDB19=Gateways\MGodbc.dll
;MGDB20=Gateways\MGmssql.dll
MGDB21=Gateways\MGmemory.dll


[MAGIC_JAVA]
JAVA_HOME=
JVM_PATH=
CLASSPATH=.;Support\*;Support\Apache-httpcomponents-client\lib\*;GigaSpaces+
-xpa\lib\xpa\*;GigaSpaces\lib\required\*;Gateways\*
JVM_ARGS=-Djava.compiler=NONE -Xms16m -Xmx256m -Dorg.xml.sax.driver=org.apa+
che.xerces.parsers.SAXParser -Dcom.gigaspaces.logger.RollingFileHandler.fil+
ename-pattern={homedir}/../Logs/GS/{date,yyyy-MM-dd~HH.mm}-gigaspaces-{serv+
ice}-{host}-{pid}.log -Dlog4j.configurationFile=%EngineDir%\GigaSpaces-xpa\+
config\log4j2.xml -Dcom.magicsoftware.xpa.home=%EngineDir% -Dcom.magicsoftw+
are.xpa.logging.module=MgxpaRuntime_GS -Dcom.magicsoftware.xpa.ServerLoadOn+
DemandTimeout=10
; -Dcom.magicsoftware.xpa.DefaultErrorFormatFileName=%EngineDir%\GigaSpaces+
-xpa\test\DefaultError.html


[MAGIC_LOGGING]
Task = N
Levels = N
DataView = N
Recompute = N
Flow = N
Events = N
LogClient = N
TransCache = N
LogSynch = N
BeginEndMsg = N
Gateway = N
BackgroundMsg = N
ExternalLogFileName =

[CRR_INTERFACES]
Webサービス = Add_On\CRR\Wizards\CRRws.ecf, InvokeWizard, WS
ストアドプロシジャ = Add_On\CRR\Wizards\CRRSp.ecf, InvokeWizard, StoredProc
MSMQ サポート = Add_On\CRR\Wizards\CRRMessaging.ecf,InvokeWizard, MSMQ

[TOOLS_MENU]
DDLBDR = A,DDLMaker(&D),,Add_On\DDLMaker\PVDDLMaker.ecf,,,Add_On\DDLMaker\D+
DLMaker_suf.opr,ImageFor = B ToolNumber = 60 ToolGroup = 1 ToolTip = +
"データ辞書を作成します."
String Extractor = A,文字列抽出(&T),,Add_On\StringExtractor\StringExtractor+
.ECF,,,,Ima+ geFor = B ToolNumber = 283 ToolGroup = 1 ToolTip = "多言語辞書+
用の文字列を抽出します."
Separator = S,,,,,,,
Upgrade Manager = O,ｱｯﾌﾟｸﾞﾚｰﾄﾞﾏﾈｰｼﾞｬ(&U),,"%EngineDir%Add_On\UpgradeManager+
\UpgradeManager.cmd" %WorkingDir%,,,,ImageFor = B ToolImage = "%EngineDir%A+
dd_On\UpgradeManager\Images\UpgradeManager.bmp" ToolGroup = 2 ToolTip = +
"Magic uniPaaS からMagic xpaへのアップグレードの結果を管理します" +
MenuShowWindow = 1

[MAGIC_BUILDERS]
ECI=Builders\ECI\
WS=Builders\WS\
Soap Server Address = http://localhost:6060
SoapUser = admin

[MAGIC_DEFAULTS]
DefaultDate = 0
NullAlphaDisplay =
NullNumericDisplay =
NullLogicalDisplay =
NullDateDisplay =
NullTimeDisplay =
NullMemoDisplay =
NullBlobDisplay =
;MergePrefix =
;MergeSuffix =


[MAGIC_DEVICES]
iPhone 4 = I, 3.5, 640, 960
iPhone 5 = I, 4.0, 640, 1136
iPhone 6 = I, 4.7, 750, 1334
iPhone 6Plus = I, 5.5, 1080, 1920
iPad mini = I, 7.9, 768, 1024
iPad = I, 9.7, 1536, 2048
Android 4.7" = A, 4.7, 720, 1280
Android 10.1" = A, 10.1, 800, 1280

[MAGIC_SPECIALS]
;ClosePrintedTablesInSubtasks=N
;MergeFlushSize=51200
;MergeTrim = Y
SpecialClientCompressMessages=Y
;SpecialConvAddSlash=N
;SpecialExcludeServerSideEnv=Y
;SpecialImageResize4Printing=Y
;SpecialPrintWhiteTillEOP=Y
;SpecialRelativeImport=N
;SpecialXMLViewCreateOptional=Y

;DisableMouseWheel=Y
;SpecialAppServerAllowVerifyInBox=Y
;SpecialCancelOnCreate= Y
;SpecialEditLeftAlign=Y
;SpecialEditIncreasedHeight=Y
;SpecialExpReturnNull=Y
;SpecialFlatEditOnClassicTheme=Y
;SpecialIgnoreBGinModify=Y
;SpecialKeyboardBuffering=Y
;SpecialLinkWriteAccess=N
;SpecialModifiedDecimalSeparator=N
;SpecialNullTerminateBlobs=Y
SpecialOldZorder=Y
;SpecialRefreshControlProperties=Y
;SpecialRestoreMaximizedForm=N
;SpecialSkipInMultiEdit=N
;SpecialTrimTrailingNulls=Y

;SpecialAnsiExpression=N
;SpecialDefaultTransactionMode = P
;SpecialExpressionAutoComplete=N
;SpecialExpressionTooltip=N
SpecialRMCompatibleLogic = Y
;SpecialSetParamRemoveEmptyStrings=Y
;SpecialShowCheckInScreen= N
;SpecialShowCheckOutScreen= N
;SpecialShowStatusBarPanes=Y
;SpecialWaitForRuntimeSimulateOperation=Y

;RtfBufferSize=1
;SpecialDatabaseConnectionPooling=Y
;SpecialNoCheckIndexInDeferred=N
;XXLNumericSize = Y
;SpecialTrimParamDSQL = Y

;ConvertJNISentNamesToUTF8=N
;ExceptionMessageBoxDisplay = N
;SpecialAddPathToRIACacheRequests=Y
SpecialClientSecureMessages=Y
;SpecialEventQMaxInterval=0
;SpecialEventQSizeLimit=0
;SpecialLogInternalExceptions=N
;SpecialLicenseLog=
;SpecialLicenseServerInterval=1
;SpecialProgXMLSizeWarning=2000
;SpecialRecordCriticalLockWait=100
;SpecialRIAEncryptAES=Y
;SpecialRIAEncryptCache=Y
;SpecialSchemaSizeLimit=20000
;SpecialSwipeFlickeringRemoval=Y
;SpecialTableCriticalLockWait=100
;SpecialV9BlobInVectorCompatible=N


[dbMAGIC_ENV]
;As400Set=N
;LocateProgramList = Y
;NoDocumentName = Y
;PrecedeProgramList = Y
;PrintLine = S
;ShowComponentError = N
;ShowItemSymbolSelect = Y
;TripletNonAsciiUrl = N
;PrintTextByteMode = Y
;GetParamAnsi = Y
;HttpCallUTF8 = Y
;IgnoreSurrogatePair = Y
;EditIncreasedWidth = Y
GENGO1=2019/05/01, ?a,R

[WINDOWSJ_PRINTER]
PrintType=WPWIN32
Device=N
Wprw=N
DirectFlat=N
EscCommand=Y
BackPrint=Y
PrintDialog=N
Message=Y
Mode=D
CharOrigin=D
CharType=P
CharHeight=18/120
CharWidth=9/120
CharPitch=4/160
FormHeight=20/120
FontName0= l r
BoldName=
FontName1=
FontName2=
FontName3=
EscapeChar=
FsChar=
SmallText=
[MAGIC_PRINTERS]
Printer1=iR-ADV C5840(白黒)/PA4,,,66
Printer2=OKI MICROLINE 5650SU3-R/PA4,,,66
Printer3=iR-ADV C5840(白黒)/PA4/OPORT/B264,,,66
Printer4=VP-4300/P15X11,,,60
Printer5=VP-4300/P15X11,wpdrv.atr,,60
Printer6=VP-4300/P15X11/OPORT,,,60
Printer7=EPSON CW-C4020/P3000/OPORT,,,66
Printer8=Microsoft Print to PDF/PA4/OPORT,wpdrv.atr,,40
Printer9=iR-ADV C5840(白黒)/PB4/OPORT,,,66
Printer10=OKI MICROLINE 5650SU3-R/PA4,,,66
;Printer20=iR-ADV C5840(白黒)/PA4,,,66
Printer20=OKI MICROLINE 5650SU3-R/PA4_ROTATED/M0X0X0X0,,,6
